apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-qdrant-storage
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
