apiVersion: v1
kind: Service
metadata:
  name: rag-qdrant
  labels:
    app: rag-qdrant
spec:
  type: ClusterIP
  selector:
    app: rag-qdrant
  ports:
    - name: http
      port: 6333
      targetPort: http
      protocol: TCP
