apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.traefik.io/traefik'
    targetRevision: 27.0.2
    chart: traefik
    helm:
      values: |
        hostNetwork: true
        deployment:
          strategy: Recreate
        livenessProbe:
          httpGet:
            host: 127.0.0.1
        readinessProbe:
          httpGet:
            host: 127.0.0.1
        additionalArguments:
          - --providers.kubernetescrd.endpoint=https://127.0.0.1:6443
          - --providers.kubernetesingress.endpoint=https://127.0.0.1:6443
        service:
          type: ClusterIP
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
